<?php
require_once __DIR__ . '/auth/auth_check.php';
require_role(['Patient']);
ensure_clinical_tables();
$errors = session_pull('errors', []); $success = session_pull('success'); $patientId = (int)$_SESSION['user_id'];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!csrf_check($_POST['_csrf'] ?? null)) { $errors[] = 'Security token expired. Please try again.'; }
    else {
        $type = trim((string)($_POST['allergy_type'] ?? '')); $name = trim((string)($_POST['name'] ?? ''));
        $reaction = trim((string)($_POST['reaction'] ?? '')); $severity = trim((string)($_POST['severity'] ?? 'Moderate')); $notes = trim((string)($_POST['notes'] ?? ''));
        if (!in_array($type, ['Drug','Food','Environmental','Other'], true) || $name === '' || mb_strlen($name) > 150 || mb_strlen($reaction) > 255 || mb_strlen($notes) > 2000 || !in_array($severity, ['Mild','Moderate','Severe'], true)) $errors[] = 'Please provide valid allergy details.';
        if (!$errors) { $stmt=db()->prepare('INSERT INTO allergies (patient_id, allergy_type, name, reaction_text, severity, notes, recorded_at) VALUES (?, ?, ?, ?, ?, ?, CURDATE())'); $stmt->execute([$patientId,$type,$name,$reaction ?: null,$severity,$notes ?: null]); $_SESSION['success']='Allergy added to your medical record.'; redirect('allergies.php'); }
    }
}
$stmt=db()->prepare('SELECT * FROM allergies WHERE patient_id=? ORDER BY is_active DESC, recorded_at DESC'); $stmt->execute([$patientId]); $allergies=$stmt->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Allergies - NHRE</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"><link rel="stylesheet" href="assets/css/styles.css"></head><body class="dashboard-body"><?php require __DIR__.'/includes/sidebar.php'; require __DIR__.'/includes/topnav.php'; ?><main class="dashboard-main"><section class="container"><div class="dashboard-hero glass-card"><div><span class="auth-kicker">Clinical Safety</span><h1>Allergies</h1><p>Maintain active drug, food, and environmental allergies for your care team.</p></div></div><?php foreach($errors as $error): ?><div class="alert alert-danger mt-3"><?=e($error)?></div><?php endforeach; ?><?php if($success): ?><div class="alert alert-success mt-3"><?=e($success)?></div><?php endif; ?><div class="row g-4 mt-1"><div class="col-lg-4"><form method="post" class="dashboard-card"><input type="hidden" name="_csrf" value="<?=csrf_token()?>"><h2 class="fs-5">Add allergy</h2><select class="form-select mb-2" name="allergy_type" required><option value="Drug">Drug</option><option value="Food">Food</option><option value="Environmental">Environmental</option><option value="Other">Other</option></select><input class="form-control mb-2" name="name" maxlength="150" placeholder="Allergen name" required><input class="form-control mb-2" name="reaction" maxlength="255" placeholder="Reaction"><select class="form-select mb-2" name="severity"><option>Mild</option><option selected>Moderate</option><option>Severe</option></select><textarea class="form-control mb-3" name="notes" maxlength="2000" placeholder="Notes"></textarea><button class="btn btn-solid-nhre w-100">Save allergy</button></form></div><div class="col-lg-8"><article class="dashboard-card"><h2 class="fs-5">Recorded allergies</h2><?php if(!$allergies): ?><p class="text-muted mb-0">No allergies recorded.</p><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>Allergen</th><th>Type</th><th>Reaction</th><th>Severity</th><th>Recorded</th></tr></thead><tbody><?php foreach($allergies as $a): ?><tr><td><?=e($a['name'])?></td><td><?=e($a['allergy_type'])?></td><td><?=e($a['reaction_text'] ?: '—')?></td><td><span class="badge bg-<?= $a['severity']==='Severe'?'danger':($a['severity']==='Moderate'?'warning text-dark':'success') ?>"><?=e($a['severity'])?></span></td><td><?=e($a['recorded_at'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></article></div></div></section></main><script src="assets/js/app.js?v=20260818-10"></script></body></html>
