<?php
require_once __DIR__ . '/auth/auth_check.php';
require_role(['Doctor']);
ensure_appointments_table_exists(); ensure_access_tables_exists();
$doctorId=(int)$_SESSION['user_id']; $q=trim((string)($_GET['q']??'')); $params=[$doctorId,$doctorId];
$sql="SELECT u.id,u.fullname,u.account_number,u.date_of_birth,u.gender,u.blood_group, MAX(a.appointment_date) AS last_appointment,
       EXISTS(SELECT 1 FROM access_permissions ap WHERE ap.patient_id=u.id AND ap.provider_id=? AND ap.status='Active' AND (ap.expires_at IS NULL OR ap.expires_at>NOW())) AS has_access
      FROM users u LEFT JOIN appointments a ON a.patient_id=u.id AND a.doctor_id=?
     WHERE u.role='Patient' AND (a.appointment_id IS NOT NULL OR EXISTS(SELECT 1 FROM access_permissions ap2 WHERE ap2.patient_id=u.id AND ap2.provider_id=? AND ap2.status='Active' AND (ap2.expires_at IS NULL OR ap2.expires_at>NOW())))";
// Bind the EXISTS access checks without exposing arbitrary patient IDs.
$params=[$doctorId,$doctorId,$doctorId];
if($q!==''){ $sql.=' AND (u.fullname LIKE ? OR u.account_number LIKE ?)'; $like='%'.$q.'%'; $params[]=$like;$params[]=$like; }
$sql.=' GROUP BY u.id ORDER BY last_appointment DESC, u.fullname ASC LIMIT 100';
$stmt=db()->prepare($sql);$stmt->execute($params);$patients=$stmt->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Patients - NHRE</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"><link rel="stylesheet" href="assets/css/styles.css"></head><body class="dashboard-body"><?php require __DIR__.'/includes/sidebar.php';require __DIR__.'/includes/topnav.php';?><main class="dashboard-main"><section class="container"><div class="dashboard-hero glass-card"><div><span class="auth-kicker">Doctor workspace</span><h1>My Patients</h1><p>Patients from your appointments or patients who granted you active record access.</p></div></div><form class="dashboard-card mt-4" method="get"><div class="d-flex gap-2"><input class="form-control" name="q" maxlength="80" value="<?=e($q)?>" placeholder="Patient name or NHRE account number"><button class="btn btn-solid-nhre">Search</button></div></form><article class="dashboard-card mt-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Patient</th><th>NHRE ID</th><th>Age / Blood</th><th>Last appointment</th><th>Access</th><th></th></tr></thead><tbody><?php foreach($patients as $p):?><tr><td><?=e($p['fullname'])?><br><small class="text-muted"><?=e($p['gender']?:'—')?></small></td><td><?=e($p['account_number']?:'—')?></td><td><?= $p['date_of_birth']?e((string)age_from_dob($p['date_of_birth'])).' years':''?> <?=e($p['blood_group']?:'')?></td><td><?=e($p['last_appointment']?:'—')?></td><td><?= $p['has_access']?'<span class="badge bg-success">Authorized</span>':'<span class="badge bg-secondary">Basic profile only</span>'?></td><td><?php if($p['has_access']):?><a class="btn btn-sm btn-solid-nhre" href="authorized_records.php?patient=<?=(int)$p['id']?>">Records</a><?php else:?><a class="btn btn-sm btn-outline-nhre" href="patient_search.php?q=<?=urlencode($p['account_number'])?>">Request access</a><?php endif;?></td></tr><?php endforeach;?><?php if(!$patients):?><tr><td colspan="6" class="text-muted">No patients match this view.</td></tr><?php endif;?></tbody></table></div></article></section></main><script src="assets/js/app.js?v=20260818-10"></script></body></html>
